services:
  - type: web
    name: fantasy-football-mcp-server
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python fastmcp_server.py"
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: true
      - key: ALLOWED_REDIRECT_URIS
        value: "https://claude.ai/api/mcp/auth_callback,https://claude.ai/oauth/callback,https://claude.ai/*"
      - key: ALLOWED_CLIENT_IDS
        value: "Claude,claude-ai,claude.ai,anthropic,mcp-client,*"
      - key: OAUTH_CLIENT_SECRET
        generateValue: true
      - key: YAHOO_CONSUMER_KEY
        sync: false
      - key: YAHOO_CONSUMER_SECRET
        sync: false
      - key: YAHOO_ACCESS_TOKEN
        sync: false
      - key: YAHOO_REFRESH_TOKEN
        sync: false
      - key: YAHOO_GUID
        sync: false
      - key: PORT
        value: 8080